config/routes.rb
Rails.application.routes.draw do

  
  resources :papers, except: [:show]
  get '/papers/:id/veja' => 'papers#show', as: :paper_show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Way to configure Root path for some controller generated by devise

  #PDF View
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  
  
  
  #get '/pdf_render' => 'application#pdf_render', as: :pdf_render


  authenticated :coordinator do
    root 'coordinators#index', as: :authenticated_coordinator_root
    get 'coordinator/pending' => 'coordinators#coordinator_pendings_papers', as: :coordinator_pendings
    get 'coordinator/onhold' => 'coordinators#coordinator_onhold_papers', as: :coordinator_onhold
    get 'coordinator/concluded' => 'coordinators#coordinator_concluded_papers', as: :coordinator_concluded
    get 'coordinator/index' => 'coordinators#index', as: :coordinator_index
    get 'coordinator/take_paper' => 'coordinators#take_paper', as: :take_paper
    get 'coordinator/return_paper' => 'coordinators#return_paper', as: :return_paper
    patch 'coordinator/allocate' => 'coordinators#allocate_reviewer', as: 'allocate_reviewer'
    get 'coordinator/desallocate' => 'coordinators#desallocate_reviewer', as: 'desallocate_reviewer'
    patch 'coordinator/concluded' => 'coordinators#concluded?', as: :concluded
    get 'coordinator/:paper_id/veja-mais' => 'coordinators#show_paper', as: :coordinator_show_paper
    get 'historico' => 'coordinators#coordinator_events', as: :coordinator_events

     # PDF VIEW
    get 'coordinator/:paper_id/pdf_render' => 'application#pdf_render'
  end
  authenticated :professor do
    get '/papers/:id/pdf_render' => 'application#pdf_render'
    root 'professors#index', as: :authenticated_professor_root
    get 'professor/pending' => 'professors#professor_pending_papers', as: :professor_pending
    get 'professor/concluded' => 'professors#professor_concluded_papers', as: :professor_concluded
    get 'professor/:paper_id/historico' => 'professors#events', as: :events
    get 'professor/index' => 'professors#index', as: :professor_index
  end
  authenticated :reviewer do
    root 'reviewers#index', as: :authenticated_reviewer_root
    get 'reviewer/pending' => 'reviewers#reviewer_pending_papers', as: :reviewer_pending
    get 'reviewer/concluded' => 'reviewers#reviewer_concluded_papers', as: :reviewer_concluded
    get 'reviewer/index' => 'reviewers#index', as: :reviewer_index
    get 'reviewer/:paper_id/edit' => 'reviewers#reviewer_edit', as: :reviewer_edit
    patch 'reviewer/edit/save' => 'reviewers#reviewer_save', as: :reviewer_save

    #PDF VIEW
    get 'reviewer/:paper_id/pdf_render' => 'application#pdf_render' 
  end
  

  
  devise_for :professors, controllers: {
    sessions: 'professors/sessions',
    passwords: 'professors/passwords'
  }
  devise_for :coordinators, controllers: {
    sessions: 'coordinators/sessions',
    passwords: 'coordinators/passwords'
  }
  devise_for :reviewers, controllers: {
    sessions: 'reviewers/sessions',
    passwords: 'reviewers/passwords'
  }

  # Login
  get 'login' => "logins#login", as: :logins
  get 'update_login_form' => "logins#update_login_form", as: :update_login_form

  # Root definition: in the end of file
  root 'logins#login'

  

end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  has_many :papers, primary_key: 'id',
                    foreign_key: 'reviewer_id'
end

app/controllers/reviewers/confirmations_controller.rb
# frozen_string_literal: true

class Reviewers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/reviewers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Reviewers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/reviewers/passwords_controller.rb
# frozen_string_literal: true

class Reviewers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/reviewers/registrations_controller.rb
# frozen_string_literal: true

class Reviewers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/reviewers/sessions_controller.rb
# frozen_string_literal: true

class Reviewers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to logins_path
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to reviewer_index_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/reviewers/unlocks_controller.rb
# frozen_string_literal: true

class Reviewers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  before_action :authenticate_reviewer!
  before_action :find_paper, only: [:reviewer_edit, :reviewer_save]
  layout 'reviewer'
  def index
    #@reviewer_papers = Paper.select{|paper| paper.reviewer_id == current_reviewer.id}
    @reviewer_papers_onhold = current_reviewer.papers.select{|paper| paper.status!='CONCLUIDA'}
    @reviewer_papers_pending = current_reviewer.papers.select{ |paper| paper.status=="REVISOR" || paper.status=="VOLTOU REVISOR"}.size
    @reviewer_papers_concluded = current_reviewer.papers.select{ |paper| paper.status=="CONCLUIDA"}.size
  end

  def reviewer_pending_papers
    @reviewer_papers_pending = current_reviewer.papers.select{ |paper| paper.status=="REVISOR" || paper.status=="VOLTOU REVISOR"}
  end
  def reviewer_concluded_papers
    @reviewer_papers_concluded = current_reviewer.papers.select{ |paper| paper.status=="CONCLUIDA"}
  end

  def reviewer_edit
  end

  def reviewer_save

    if @paper.update(status: 'DEVOLVIDO', reviewed_file_key: params[:paper][:reviewed_file_key])
      Event.create(log: 'Devolvido para o coordenador. Revisor concluiu a revisão', paper_id: @paper.id)
      redirect_to reviewer_index_path, notice: 'Estado atualizado com sucesso.'
    else
      redirect_to reviewer_index_path, notice: 'Não foi possível atualizar o estado deste artigo'
    end
  end

  private

  def find_paper
    @paper = Paper.find(params[:paper_id])
  end
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
  def paper_reviewer_status(status)
    if status == 'SUBMETIDO'
      @status = 'Submetido para revisão'
    end
    if status == 'RECEBIDO'
      @status  = 'Recebido pelo coordenador'
    end
    if status == 'REVISOR'
      @status = 'Enviado para você'
    end
    if status == 'DEVOLVIDO'
      @status = 'Devolvido para o coordenador'
    end
    if status == 'VOLTOU REVISOR'
      @status = 'O Artigo voltou para você'  
    end
    if status == 'CONCLUIDA'
      @status = 'Revisão concluída'
    end
    return @status
  end 
end

app/views/reviewers/index.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });

    var dataTable = $("#reviewer-paper-table").DataTable();
  })
</script>
<p><%= notice%></p>
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">
        <p><i class="fas fa-calendar-minus"></i>
          <%= @reviewer_papers_pending %> 
          Pendências
        </p>
      </div>
      <div class="panel-footer">
        <%= link_to reviewer_pending_path,  class: 'btn btn-default' do %>
          Ver Artigos <i class="fas fa-arrow-circle-right"></i> 
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-default text-center">
      <div class="panel-body">
        <p><i class="fas fa-calendar-check"></i>
          <%= @reviewer_papers_concluded %> 
          Revisões Concluídas
        </p>
      </div>
      <div class="panel-footer">
        <%= link_to reviewer_concluded_path,  class: 'btn btn-default' do %>
          Ver Artigos <i class="fas fa-arrow-circle-right"></i> 
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <p><b>ARTIGOS NO PROCESSO DE REVISÃO</b></p>
        <table id="reviewer-paper-table">
          <thead>
            <tr>
              <th>Título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em</th>
              <th>Edição</th>
            </tr>
          </thead>
          <tbody>
            <% @reviewer_papers_onhold.each do |paper|%>
              <tr>
                <td><%= paper.title %></td>
                <td><%= paper.professor.name%></td>
                <td><%= paper_reviewer_status(paper.status) %></td>
                <td><%= paper.updated_at %></td>
                <td><%= link_to 'Ver Mais', reviewer_edit_path(:paper_id => paper.id), class: 'btn btn-info' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/reviewers/reviewer_concluded_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    
    var dataTable = $("#reviewer-paper-concluded-table").DataTable();
  })
</script>
<div class="row">
  <div class="col-md-12">
    <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <p><b>TODOS SEUS ARTIGOS</b></p>
        <table id="reviewer-paper-concluded-table">
          <thead>
            <tr>
              <th>Título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em</th>
              <th>Edição</th>
            </tr>
          </thead>
          <tbody>
            <% @reviewer_papers_concluded.each do |paper|%>
              <tr>
                <td><%= paper.title %></td>
                <td><%= paper.professor.name%></td>
                <td><%= paper_reviewer_status(paper.status) %></td>
                <td><%= paper.updated_at %></td>
                <td><%= link_to 'Ver Mais', reviewer_edit_path(:paper_id => paper.id), class: 'btn btn-info' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/reviewers/reviewer_edit.html.erb
<%= javascript_include_tag 'form_validate' %>
<%= javascript_include_tag 'pdf-modal' %>
<% puts @paper.status %>
<div id="pdf-view"></div>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-10">
    <% if @paper.status == 'CONCLUIDA'%>
      <p><%= link_to 'Voltar', reviewer_concluded_path, class: 'btn btn-info'%></p>
    <%elsif @paper_status =='REVISOR' || @paper.status == 'VOLTOU REVISOR'%>
      <p><%= link_to 'Voltar', reviewer_pending_path, class: 'btn btn-info'%></p>
    <% else%>
      <p><%= link_to 'Voltar', reviewer_pending_path, class: 'btn btn-info'%></p>
    <% end %>
  </div>
</div>

<% puts @paper.status %>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p class="text-center"><%= @paper.title.upcase%></p>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Professor: </b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left"><%= @paper.professor.name%></p>
          </div>
        </div>
        <% if @paper.coordinator != nil%>
          <div class="row">
            <div class="col-md-4">
              <p><b>Coordenador:</b></p>
            </div>
            <div class="col-md-8">
              <p><%= @paper.coordinator.name%></p>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Estado: </b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left"><%= @paper.status%></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Artigo Original: </b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left">
              <%= link_to @paper.original_file_key.url, target: :_blank, class: 'btn btn-primary' do %>
                <i class="fas fa-download"></i>
                Baixar
              <% end %>
            </p>
          </div>
        </div>


        <% if @paper.status=='DEVOLVIDO' || @paper.status=='CONCLUIDA' || @paper.status=='VOLTOU REVISOR' %>
          <div class="row">
            <div class="col-md-4">
              <p class="text-left"><b>Artigo Revisado: </b></p>
            </div>
            <div class="col-md-8">
              <p class="text-left">
                <%= link_to @paper.reviewed_file_key.url, target: :_blank, class: 'btn btn-primary' do %>
                  <i class="fas fa-download"></i>
                  Baixar
                <% end %>
              </p>
            </div>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Enviar Artigo: </b></p>
          </div>
          <div class="col-md-8">
            <% if @paper.status != 'CONCLUIDA'%>
              <%=form_for @paper, :url => reviewer_save_path(:paper_id => @paper.id) do |f|%>
                <%= f.file_field :reviewed_file_key, class: 'btn btn-primary' %>
                <div class="reviewer-checkbox">
                  <%= f.check_box :status, {}, 'DEVOLVIDO', 'REVISOR' %> Revisão Concluída
                </div>
                <div>
                  <%= f.submit 'Atualizar', class: 'reviewer-paper-button btn btn-primary'%>
                </div>
              <% end %>
              <% else %>
                <p class="two-column-left"><b>Concluído em: </b></p>
                <p class="two-column-right"><%= @paper.updated_at %></p>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/reviewers/reviewer_pending_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#reviewer-paper-pending-table").DataTable();
  })
</script>
<div class="row">
  <div class="col-md-12">
    <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <p><b>TODOS SEUS ARTIGOS</b></p>
        <table id="reviewer-paper-pending-table">
          <thead>
            <tr>
              <th>Título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em</th>
              <th>Edição</th>
            </tr>
          </thead>
          <tbody>
            <% @reviewer_papers_pending.each do |paper|%>
              <tr>
                <td><%= paper.title %></td>
                <td><%= paper.professor.name%></td>
                <td><%= paper_reviewer_status(paper.status) %></td>
                <td><%= paper.updated_at %></td>
                <td><%= link_to 'Ver Mais', reviewer_edit_path(:paper_id => paper.id), class: 'btn btn-info' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>